### ISSUE TITLE
May be expected behavior?  

### ISSUE THREAD

**Issue by ariperez** [GSA/search.digitalgov.gov#2]
Entering these credentials:

![image](https://cloud.githubusercontent.com/assets/2553469/8131110/128d14dc-10e6-11e5-9737-0ce296fa3992.png)

Routes you to here:

![image](https://cloud.githubusercontent.com/assets/2553469/8131125/30ac87e0-10e6-11e5-9578-53e256ffb3fd.png)

**Comment by awichman** [comment]
This workflow has changed: users are no longer redirected to USA.gov during unsuccessful log in attempts.
