### ISSUE TITLE
Education Department link in Our Customers post is dead

### ISSUE THREAD

**Issue by knowtheory** [GSA/search.digitalgov.gov#36]
Hey y'all,

Check out the [`Our Customers`](https://search.gov/customers.html) post ([this appears to be the source](https://github.com/GSA/search.digitalgov.gov/blob/1bc3ac08fb91c2cda1d5ad5cc986721f4b36eebc/_posts/2017-03-02-customers.md)).  The Education Dept link doesn't go anywhere (and the search box on ed.gov still points to search.usa.gov )

Just wanted to let you know!

**Comment by dawnpm** [comment]
Thanks @knowtheory we'll take a look at this issue and other updates needed for that page. Closing the issue out now.
