### ISSUE TITLE
Community efforts

### ISSUE THREAD

**Issue by brennv** [GSA/search.digitalgov.gov#7]
Is there a certain space for sharing community efforts? Disclaimer, I recently wrote [this](https://github.com/brennv/usajobs) simple python client for usajobs. ...I was about to fork [this post](https://github.com/GSA/search.digitalgov.gov/blob/master/_posts/2015-09-17-jobs.md) but I thought I'd check first.

**Comment by dawnpm** [comment]
We do not post information about community efforts, unfortunately.
