### ISSUE TITLE
Improve performance of loading remote.loader.js?

### ISSUE THREAD

**Issue by anselmbradford** [GSA/search.digitalgov.gov#9]
https://github.com/GSA/search.digitalgov.gov/blob/master/drafts/2015-08-31-code.md#2-javascript-snippet is [used on consumerfinance.gov](https://github.com/cfpb/cfgov-refresh/blob/master/cfgov/jinja2/v1/_layouts/base.html#L279). A recent analysis of the site with Google's Lighthouse performance audit tool showed this script is a top bottleneck in render-blocking scripts:

![screen shot 2017-09-28 at 2 58 14 pm](https://user-images.githubusercontent.com/704760/30985228-b257f1c8-a45d-11e7-9c9e-72870c8b7091.png)

Delaying paint by almost 4 times that of modernizr, which is a much larger library. 

Possibly this is moot due to the position of the script on the page, but are there options to make the loading time faster? Could it be distributed as a node module that's included locally or is there a more performant way it could be set up via a CDN?

**Comment by dawnpm** [comment]
Hello! thank you for reporting this. We tweaked a backend setting for you that should help a lot, and will also be investigating the issue more generally.

**Comment by dawnpm** [comment]
@anselmbradford I'm going to close out this issue, since the backend change is in effect now. Thanks.

**Comment by anselmbradford** [comment]
Okay! We don't see a difference in our lighthouse report, but perhaps that's on our side. Did you'll see a difference with the backend changes?

**Comment by dawnpm** [comment]
Hm, perhaps we should connect directly to look at what you're seeing. On our side, we saw that a now-unused functionality of the js was still enabled for your site, and it seemed obvious this was what was causing the slowness, so we disabled it. 

Please reach out to search@support.digitalgov.gov and we can set up a time to meet/screenshare. Thanks!
